<?php
	return array(
			
			# G E N E R A L S
			'fields with * are required'=>'Les champs avec * sont réquis',
			'required field(s) cannot be left empty'=>'Tous les champs réquis ne peuvent être laissé vide',
			'sign in'=>'Connexion',
			'sign out'=>'Déconnexion',
			'lock screen'=>'Verrouillé',
			'password'=>'Mot de passe',
			'submit'=>'Soumettre',
			'cancel'=>'Annuler',
			'back'=>'Arrière',
			'search'=>'Recherche',
			'preview'=>'Aperçu',
			'continue'=>'Continuer',
			'dashboard'=>'Tableau De Bord',
			'dashboard'=>'Tableau',
			'gender'=>'Sexe',
			'day'=>'Jour',
			'month'=>'Moi',
			'year'=>'Année',
			'today'=>'Aujourd\'hui',
			'this month'=>'Ce mois',
			'this year'=>'Cette Année',
			'remove'=>'Enlever',
			'remove photo'=>'Enlever Photo',
			'edit'=>'Modifier',
			'yes'=>'Oui',
			'no'=>'Non',
			'by'=>'Par',
			'accepted formats: gif, png, jpg. max file size 2mb'=>'Formats acceptés: gif, png, jpg. Taille max 2Mb',
			'are you sure'=>'Etes-vous sûre',
			'name'=>'Nom',
			'create'=>'Créer',
			'save'=>'Sauvegarder',
			'empty'=>'Vide',
			'occupied'=>'Occupé',
			'from'=>'Du',
			'to'=>'au',
			'filter'=>'Trier',
			'activate'=>'Activater',
			'deactivate'=>'Désactiver',
			'delete'=>'Supprimer',
			'active'=>'Actif',
			'inactive'=>'Inactif',
			'deleted'=>'Supprimé',
			'with selected'=>'Avec sélectionné',
			'proceed'=>'Procéder',
			'choose'=>'Choisir',
			'view'=>'Vue',
			'manage'=>'Gérer',
			'all'=>'Tout',
			'for'=>'Pour',
			'user'=>'Utilisateur',
			'value must be between'=>'La valeur doit être entre',
			'and'=>'et',
			'required'=>'Obligatoire',
			'add new'=>'Ajouter nouveau',
			'separate with a comma'=>'Séparer par une virgule',
			'date of birth'=>'Date de naissance',
			'no records found'=>'Aucun enregistrements trouvé',
			'current'=>'Actuel',
			'new'=>'Nouveau',
			'confirm'=>'Confirmer',
			'creation date'=>'Date de création',
			'close'=>'Fermer',
			'fullname'=>'Nom complet',
			
			
			# A L E R T S
			'has been added'=>'a été ajouté(e)',
			'has been edited'=>'a été modifié(e)',
			'has been activated'=>'a été activé(e)',
			'has been deactivated'=>'a été désactivé(e)',
			'has been deleted'=>'a été supprimé(e)',
			'has been emptied'=>'a été vidé(e)',
			'with password'=>'avec pour mot de passe',
			'transaction completed'=>'Transaction réussie',
			'invalid credentials'=>'Données incorrectes',
			'invalid code'=>'Code incorrect',
			'already exists. please choose another'=>'existe déjà. Veullez en saisir un autre',
			
			
			# F O R M S
			'first name'=>'Prénom',
			'other name'=>'Autres noms',
			'last name'=>'Nom de famille',
			'Date of birth'=>'Date de Naissance',
			'place of birth'=>'Lieu de Naissance',
			'male'=>'Masculin',
			'female'=>'Feminin',
			'blood group'=>'Groupe Sanguin',
			'nationality'=>'Nationalité',
			'religion'=>'Réligion',
			'category'=>'Catégorie',
			'choose'=>'Choisir',
			'address'=>'Adrèsse',
			'country'=>'Pays',
			'select country'=>'Choisir Pays',
			'state'=>'Région',
			'city'=>'Ville',
			'post code'=>'Adrèsse Postale',
			'phone'=>'Numéro',
			
			
			# S I G N I N
			'username'=>'Nom d\'utlisateur',
			'secure login'=>'Connexion Sécurisée',
			'you are now signout out'=>'Vous êtes maintenant déconnecter',
			'your licence has expired'=>'Votre licence a expiré',
			'you are no more part of the system. please contact your administrator'=>'Vous ne faites plus partie du système. Veillez contacter l\'administrateur',
			'password successfully changed. please sign in to continue'=>'Mot de passe changé avec success. Veillez vous reconnecter',
			'your session has expired. please login'=>'Votre session a expiré. Veillez-vous connecter',
			
);
